export const team = ['Allan Ibutiti',
'Damilare Olatuboson',
'Ayobami Adelakun',
'Ejiro Ogidigbo',
'Gbenga Oshinaga',
'Kati Frantz',
'Kayode Ayelegun',
'Michael Umanah',
'Victor Adukwu',
'Felix Mathia',
'Paul Kariuki',
'Francis Kipchumba',
'Olayemi Lawal',
'Sonia Karungi',
'Iyke Nwankwo',
'Anaeze Nsoffor',
'Roger Okello',
'Stephen Akinyemi',
'Olusola Oseni',
'Anyama Richard',
'Idrees Ibraheem'
];
